version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - .:/app
    links:
#    - memcached
    - postgres
#  memcached:
#    image: memcached
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
